// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjRo4swEDSMPUu188ce79S1YdVkEDauuE',
    appId: '1:403833912352:web:2745c942f34ff035495045',
    messagingSenderId: '403833912352',
    projectId: 'locusameowus',
    authDomain: 'locusameowus.firebaseapp.com',
    storageBucket: 'locusameowus.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtiQl2CIAPBSvB1LtO4FEPD7nhO86LEh4',
    appId: '1:403833912352:android:6f73c9ef584ceac3495045',
    messagingSenderId: '403833912352',
    projectId: 'locusameowus',
    storageBucket: 'locusameowus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClx_jzvehqhQW-Ne_WafqBICF8SrJ77Z4',
    appId: '1:403833912352:ios:4597908e7e7c9086495045',
    messagingSenderId: '403833912352',
    projectId: 'locusameowus',
    storageBucket: 'locusameowus.firebasestorage.app',
    iosBundleId: 'com.example.locusameowus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClx_jzvehqhQW-Ne_WafqBICF8SrJ77Z4',
    appId: '1:403833912352:ios:4597908e7e7c9086495045',
    messagingSenderId: '403833912352',
    projectId: 'locusameowus',
    storageBucket: 'locusameowus.firebasestorage.app',
    iosBundleId: 'com.example.locusameowus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjRo4swEDSMPUu188ce79S1YdVkEDauuE',
    appId: '1:403833912352:web:b730cbd3f9472a4f495045',
    messagingSenderId: '403833912352',
    projectId: 'locusameowus',
    authDomain: 'locusameowus.firebaseapp.com',
    storageBucket: 'locusameowus.firebasestorage.app',
  );
}
